name: Test Story
description: Create a structured user story for testing.
title: "[Story]: "
labels: ["test-story"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for opening a new test story! Please fill out the structured sections below.

  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: As a user, I want to... so that...
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Detail the criteria required for this story to be considered complete.
      value: |
        - [ ] 
        - [ ] 
        - [ ]
      placeholder: |
        - [ ] Requirement 1
        - [ ] Requirement 2